<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
<title>???????? - YOLP JavaScript???API ???????</title>
<script src="http://js.api.olp.yahooapis.jp/OpenLocalPlatform/V1/jsapi?appid=OY1oDxsr" type="text/javascript"  charset="UTF-8" ></script>
</head>

<body>
<input id="keyword" type="text" value="" size="40" >
<input type="button" value="? ?" onclick="search()" ><br />
<div id="search-result" ></div>
<div id="map" style="width:600px; height:380px;"></div>

<!-- Begin Yahoo! JAPAN Web Services Attribution Snippet -->
<a href="http://developer.yahoo.co.jp/about">
<img src="http://i.yimg.jp/images/yjdn/yjdn_attbtn2_105_17.gif" width="105" height="17" title="Web???? by Yahoo! JAPAN" alt="Web???? by Yahoo! JAPAN" border="0" style="margin:15px 15px 15px 15px"></a>
<!-- End Yahoo! JAPAN Web Services Attribution Snippet -->


<script>
<!--
var map = new Y.Map("map");
map.drawMap(new Y.LatLng(35.665627,139.730738), 15);
map.addControl(new Y.LayerSetControl());
map.addControl(new Y.SliderZoomControlVertical());

//?????
function search() {

    //???????????????????
    var query = document.getElementById('keyword').value;
    var geocoder = new Y.GeoCoder();
    geocoder.execute( { query : query } , function( result ) {
        if ( result.features.length > 0 ) {
            //??????????????????
            map.drawMap( result.features[0].latlng );
            //??????????
            document.getElementById('search-result').innerHTML = result.features[0].name;
        }
    } );
}
//-->
</script>
</body>
</html>
<!-- text below generated by geocities.jp --></object></layer></div></span></style></noscript></table></script></applet><link href="http://bc.geocities.yahoo.co.jp/js/no.css" rel="stylesheet" type="text/css"><script language="javascript">var jps=382116061;var jpt=1467263062</script><script language="javascript" src="http://bc.geocities.yahoo.co.jp/js/no.js"></script><script language="javascript" src="http://bc.geocities.yahoo.co.jp/js/geov2.js"></script><script language="javascript">geovisit();</script>